Home work 3.
SergIT85/IntensivStart pull request #3
Opened 2022-12-13 08:20 UTC by SergIT85

Сделаны xml:
Создан сетевой слой.
Привязаны и созданы все поля и списки
- не сделано детали фильма. API не выдаёт данные
- Проскакивает NPE на получении данных с сервера. возможно не дожидается ответа. Надо доделать в параллели с ожиданием думаю coroutines или RXJava + прописать защиту от NPE. простой ? не работает.

2022-12-13 22:10 UTC, AndroidStudentClub requested changes
Проверил - написал ряд идей для улучшений

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
Там же запросы по https -так что это лишнее - или это снифера?

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +    private const val BASE_URL = "https://api.themoviedb.org/3/"
В целом, хорошей практикой является вынесение базового урл в build.gradle 

Это может пригодится, когда у нас разные урл (например один для тестового билда/второй для настоящего который в проде)

Вот статья на эту тему [https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6](https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6)Смотреть пункт [#3](https://github.com/dfyz8-g/MoviesApp/pull/3) Way: Using Gradle Build Config Fields

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +    private const val BASE_URL = "https://api.themoviedb.org/3/"
То есть в build.gradle надо добавить поле:
`    buildConfigField "String", 'BASE_URL', "\"https://api.themoviedb.org/3/\""`

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +    private const val BASE_URL = "https://api.themoviedb.org/3/"
И потом использовать BASE_URL из сгенерированного BuildConfig:
BuildConfig.BASE_URL

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +            .baseUrl(BASE_URL)
BuildConfig.BASE_URL

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +    @GET("movie/{movie_id}/")
Обсудили, на всякий случай тут напишу, что нужно убрать слэш
поменять @GET("movie/{movie_id}/") на @GET("movie/{movie_id}") те без слэша

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("api_key") apiKey: String,
Для всех запросов параметры api_key и язык можно указать как дефолтные аргументы - чтобы не повторять их постоянно при запросах

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +        val getMovieNowPlaying = MovieApiClient.apiClient.getMovieNowPlaying(THE_MOVIE_DATABASE_API,
Для всех запросов параметры api_key и язык можно указать как дефолтные аргументы - чтобы не повторять их постоянно при запросах

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +        val getMoviePopular = MovieApiClient.apiClient.getMoviePopular(THE_MOVIE_DATABASE_API,
Для всех запросов параметры api_key и язык можно указать как дефолтные аргументы - чтобы не повторять их постоянно при запросах

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +            requireArguments().getInt("id"), THE_MOVIE_DATABASE_API,
"id" нужно в константы вынести

2022-12-13 22:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +        // Список актёров. тоже нет в api
Так в методе же /movie/{movie_id}/credits есть список актеров. Ну это пока не обязательно их отображать - но если есть желание, сделать можно

2022-12-15 01:06 UTC, SergIT85 commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +    private const val BASE_URL = "https://api.themoviedb.org/3/"
Прочитал. отличное решение, но почему то не работает. буду разбираться потом, а то отстаю уже от уроков.

2022-12-15 01:08 UTC, SergIT85 commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
Да но без этого не выходит на сервер API

2022-12-15 11:23 UTC, merged